config/routes.rb
Rapidfire::Engine.routes.draw do
  resources :question_groups do
    get 'results', on: :member
    post "update_positions", on: :member
    get 'duplicate', on: :member
    get :final, :on => :member
    resources :questions
    resources :fieldsets
    resources :answer_groups, only: [:new, :show, :create, :edit, :update]
  end
  root :to => "question_groups#index"
end

app/models/rapidfire/answer.rb
module Rapidfire
  class Answer < ActiveRecord::Base
    belongs_to :question
    belongs_to :answer_group, inverse_of: :answers

    validates :question, :answer_group, presence: true
    validate :verify_answer_text, :if => "question.present?"

    # has_attached_file :document
    # do_not_validate_attachment_file_type :document

    has_many :documents, :dependent => :destroy
    accepts_nested_attributes_for :documents, :allow_destroy => true

    if Rails::VERSION::MAJOR == 3
      attr_accessible :question_id, :answer_group, :answer_text, :documents, :documents_attributes
    end

    def right?
      if self.question.right_answers
        if self.question.type == "Rapidfire::Questions::Checkbox"
          self.question.right_answers.split("\r\n").sort == self.answer_text.split(',').sort
        else
          self.question.right_answers.split("\r\n").include? self.answer_text
        end
      else
        true
      end
    end

    private
    def verify_answer_text
      question.validate_answer(self)
    end
  end
end

app/models/rapidfire/answer_group.rb
module Rapidfire
  class AnswerGroup < ActiveRecord::Base
    belongs_to :question_group
    belongs_to :user, polymorphic: true
    has_many   :answers, inverse_of: :answer_group, autosave: true

    if Rails::VERSION::MAJOR == 3
      attr_accessible :question_group, :user
    end


    def points
      total = 0
      answers.each do |answer|
        total += answer.right? ? answer.question.points : 0
      end
      total
    end
  end
end

app/models/rapidfire/document.rb
module Rapidfire
  class Document < ActiveRecord::Base
    belongs_to :answer

    has_attached_file :asset
    do_not_validate_attachment_file_type :asset
  end
end

app/models/rapidfire/fieldset.rb
module Rapidfire
  class Fieldset < ActiveRecord::Base
    belongs_to :question_group, :inverse_of => :fieldsets

    if Rails::VERSION::MAJOR == 3
      attr_accessible :question_group, :title, :title_cn, :description, :position, :private
    end
  end
end

app/models/rapidfire/question.rb
module Rapidfire
  class Question < ActiveRecord::Base
    belongs_to :question_group, :inverse_of => :questions
    has_many   :answers, :dependent => :destroy

    default_scope { order(:position) }

    validates :question_group, :question_text, :presence => true
    serialize :validation_rules

    has_attached_file :file

    belongs_to :question_condition, :class_name => Rapidfire::Question

    as_enum :clear, :none => 0, :both => 1

    if Rails::VERSION::MAJOR == 3
      attr_accessible :question_group, :question_text, :validation_rules, :answer_options, :right_answers, :points, :show_in_pdf, :question_text_cn
      attr_accessible :question_condition_id, :question_condition_answers, :col_size, :clear_cd, :private
    end

    def self.inherited(child)
      child.instance_eval do
        def model_name
          Question.model_name
        end
      end

      super
    end

    def rules
      validation_rules || {}
    end

    def mandatory?
      if rules[:presence] == "1"
        true
      else
        false
      end
    end

    # answer will delegate its validation to question, and question
    # will inturn add validations on answer on the fly!
    def validate_answer(answer)
      if rules[:presence] == "1"
        answer.validates_presence_of :answer_text
      end

      if rules[:minimum].present? || rules[:maximum].present?
        min_max = { minimum: rules[:minimum].to_i }
        min_max[:maximum] = rules[:maximum].to_i if rules[:maximum].present?

        answer.validates_length_of :answer_text, min_max
      end
    end
  end
end

app/models/rapidfire/question_group.rb
module Rapidfire
  class QuestionGroup < ActiveRecord::Base
    belongs_to :user
    has_many  :questions, :dependent => :destroy
    has_many  :fieldsets, :dependent => :destroy
    validates :name, :presence => true

    before_destroy :destroy_answer_groups

    as_enum :type, :examen => 1, :formulaire => 0

    if Rails::VERSION::MAJOR == 3
      attr_accessible :name, :type_cd, :type, :header, :final_text, :final_link
    end

    def points
      total = 0
      questions.each do |q|
        total += q.points
      end
      total
    end

    def elements
      (questions + fieldsets).sort_by do |e|
        e.position || (questions + fieldsets).count
      end
    end

    def destroy_answer_groups
      AnswerGroup.where(:question_group_id => self.id).destroy_all
    end
  end
end

app/models/rapidfire/questions/checkbox.rb
module Rapidfire
  module Questions
    class Checkbox < Rapidfire::Question
      validates :answer_options, :presence => true

      def options
        answer_options.split(/\r?\n/)
      end

      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          answer.answer_text.split(",").each do |value|
            answer.errors.add(:answer_text, :invalid) unless options.include?(value)
          end
        end
      end
    end
  end
end

app/models/rapidfire/questions/date.rb
module Rapidfire
  module Questions
    class Date < Rapidfire::Question
      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          begin  ::Date.parse(answer.answer_text.to_s)
          rescue ArgumentError => e
            answer.errors.add(:answer_text, :invalid)
          end
        end
      end
    end
  end
end

app/models/rapidfire/questions/datetime.rb
module Rapidfire
  module Questions
    class Datetime < Rapidfire::Question
      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          begin  ::DateTime.parse(answer.answer_text.to_s)
          rescue ArgumentError => e
            answer.errors.add(:answer_text, :invalid)
          end
        end
      end
    end
  end
end

app/models/rapidfire/questions/email.rb
module Rapidfire
  module Questions
    class Email < Rapidfire::Question
      def validate_answer(answer)
        super(answer)
        if rules[:presence] == "1" || answer.answer_text.present?
          answer.errors.add(:answer_text, :invalid) unless answer.answer_text =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
        end
      end
    end
  end
end

app/models/rapidfire/questions/file.rb
module Rapidfire
  module Questions
    class File < Rapidfire::Question
    end
  end
end

app/models/rapidfire/questions/long.rb
module Rapidfire
  module Questions
    class Long < Rapidfire::Question
    end
  end
end

app/models/rapidfire/questions/radio.rb
module Rapidfire
  module Questions
    class Radio < Select
    end
  end
end

app/controllers/rapidfire/answer_groups_controller.rb
module Rapidfire
  class AnswerGroupsController < Rapidfire::ApplicationController
    before_filter :find_question_group!

    def show
      @answer_group_builder = AnswerGroupBuilder.new(answer_group_params)
      @answer_group = AnswerGroup.find(params[:id])

      respond_to do |format|
        format.html
        format.pdf do
          render :pdf => "file_name", 
            :footer => { :right => '[page] of [topage]' },
            :show_as_html => false
        end
      end
    end

    def new
      @answer_group_builder = AnswerGroupBuilder.new(answer_group_params)

      respond_to do |format|
        format.html
        format.pdf do
          render :pdf => "file_name", 
            :footer => { :right => '[page] of [topage]' },
            :show_as_html => false
        end
      end
    end

    def create
      @answer_group_builder = AnswerGroupBuilder.new(answer_group_params)
      if @answer_group_builder.save
        if !@answer_group_builder.question_group.final_text.blank?
          redirect_to final_question_group_path(@answer_group_builder.question_group)
        elsif !@answer_group_builder.question_group.final_link.blank?
          redirect_to @answer_group_builder.question_group.final_link
        else
          redirect_to question_groups_path
        end
      else
        render :new
      end
    end

    def edit
      @answer_group_builder = AnswerGroupBuilder.new(answer_group_params)
      @answer_group = AnswerGroup.find(params[:id])
    end

    def update
      @answer_group = AnswerGroup.find(params[:id])

      params[:answer_group].each do |question_id, answer_attributes|
        if answer = @answer_group.answers.find { |a| a.question_id.to_s == question_id.to_s }
          text = answer_attributes[:answer_text]
          answer.answer_text = text.is_a?(Array) ? strip_checkbox_answers(text).join(',') : text
          #answer.answer_text = text.is_a?(Array) ? text.join(',') : text

          if answer.question.type == "Rapidfire::Questions::File"
            answer.documents_attributes = answer_attributes[:documents_attributes]
          end
        else
          answer = Answer.new(:question_id => question_id)

          text = answer_attributes[:answer_text]
          answer.answer_text = text.is_a?(Array) ? strip_checkbox_answers(text).join(',') : text
          #answer.answer_text = text.is_a?(Array) ? text.join(',') : text

          if answer.question.type == "Rapidfire::Questions::File"
            answer.documents_attributes = answer_attributes[:documents_attributes]
          end

          @answer_group.answers << answer
        end
      end
      if @answer_group.save
        if !@answer_group.question_group.final_text.blank?
          redirect_to final_question_group_path(@answer_group.question_group)
        elsif !@answer_group.question_group.final_link.blank?
          redirect_to @answer_group.question_group.final_link
        else
          redirect_to question_groups_path, :notice  => "Successfully updated."
        end
      else
        render :action => 'edit'
      end
      # if @answer_group.update_attributes(params[:answer_group])
      #   redirect_to question_groups_path, :notice  => "Successfully updated."
      # else
      #   render :action => 'edit'
      # end
    end

    private

    def strip_checkbox_answers(text)
      text.reject(&:blank?).reject { |t| t == "0" }
    end
    
    def find_question_group!
      @question_group = QuestionGroup.find(params[:question_group_id])
    end

    def answer_group_params
      answer_params = { params: params[:answer_group] }
      answer_params.merge(user: current_user, question_group: @question_group)
    end
  end
end

app/controllers/rapidfire/application_controller.rb
module Rapidfire
  class ApplicationController < ::ApplicationController
    helper_method :can_administer?

    def authenticate_administrator!
      unless can_administer?
        raise Rapidfire::AccessDenied.new("cannot administer questions")
      end
    end
  end
end

app/controllers/rapidfire/fieldsets_controller.rb
module Rapidfire
  class FieldsetsController < Rapidfire::ApplicationController
    respond_to :html, :js

    before_filter :find_question_group!
    before_filter :find_fieldset!, :only => [:edit, :update, :destroy]

    def new
      @fieldset = Rapidfire::Fieldset.new(:question_group => @question_group)
      @fieldset.position = @question_group.elements.count
      respond_with(@fieldset)
    end

    def create
      #form_params = params[:fieldset].merge(:question_group => @question_group)
      @fieldset = Rapidfire::Fieldset.new(ad_params.merge(:question_group => @question_group))
      @fieldset.save

      respond_with(@fieldset, location: index_location)
    end

    def edit
      respond_with(@fieldset)
    end

    def update
      #form_params = params[:fieldset].merge(:fieldset => @fieldset)
      @fieldset.update_attributes(ad_params)

      respond_with(@fieldset, location: index_location)
    end

    def destroy
      @fieldset.destroy

      respond_with(@fieldset, location: index_location)
    end

    private
    def ad_params
      params.require(:fieldset).permit(:question_group, :title, :title_cn, :description, :position, :private)
    end

    def find_question_group!
      @question_group = QuestionGroup.find(params[:question_group_id])
    end

    def find_fieldset!
      @fieldset = @question_group.fieldsets.find(params[:id])
    end

    def index_location
      rapidfire.question_group_questions_url(@question_group)
    end
  end
end

app/controllers/rapidfire/question_groups_controller.rb
module Rapidfire
  class QuestionGroupsController < Rapidfire::ApplicationController
    before_filter :authenticate_administrator!, except: [:final]
    respond_to :html, :js
    respond_to :json, only: :results

    def index
      @question_groups = QuestionGroup.all
      respond_with(@question_groups)
    end

    def new
      @question_group = QuestionGroup.new
      respond_with(@question_group)
    end

    def create
      @question_group = QuestionGroup.new(question_group_params)
      @question_group.user = current_user
      
      if @question_group.save

      #respond_with(@question_group, location: rapidfire.question_groups_url)

        redirect_to question_group_questions_path(@question_group)
      else
        render :new
      end
    end

    def final
      @question_group = QuestionGroup.find(params[:id])
    end

    def edit
      @question_group = QuestionGroup.find(params[:id])
      respond_with(@question_group)
    end

    def update_positions
      @question_group = QuestionGroup.find(params[:id])

      if !params[:positions][:questions].nil?
        params[:positions][:questions].each do |element_id, position|
          Question.find(element_id).update_attributes(:position => position)
        end
      end

      if !params[:positions][:fieldsets].nil?
        params[:positions][:fieldsets].each do |element_id, position|
          Rapidfire::Fieldset.find(element_id).update_attributes(:position => position)
        end
      end
      redirect_to question_group_questions_path(@question_group), :notice  => "Positions mises à jour"
    end

    def duplicate
      model = QuestionGroup.find(params[:id])
      @question_group = model.dup
      @question_group.name = "Copie de #{@question_group.name}"
      model.questions.each do |question|
        @question_group.questions << question.dup
      end

      if @question_group.save
        redirect_to edit_question_group_path(@question_group)
      end
    end

    def update
      @question_group = QuestionGroup.find(params[:id])
      params.permit!
      if @question_group.update_attributes(params[:question_group])
        redirect_to question_groups_path, :notice  => "Successfully updated."
      else
        render :action => 'edit'
      end
    end

    def destroy
      @question_group = QuestionGroup.find(params[:id])
      @question_group.destroy

      respond_with(@question_group)
    end

    def results
      @question_group = QuestionGroup.find(params[:id])
      @answer_groups = Rapidfire::AnswerGroup.where(:question_group => params[:id])
      @question_group_results = QuestionGroupResults.new(question_group: @question_group).extract

      respond_to do |format|
        format.html { respond_with(@question_group_results, root: false) }
        format.xls do
          p = Axlsx::Package.new
          p.workbook.add_worksheet(:name => "Résultats") do |sheet|
            column_names = []
            @question_group.questions.each do |question|
              if @question_group.examen? && (question.points && question.points > 0)
                column_names << "#{question.question_text} [#{question.points.prettify} points]"
              else
                column_names << question.question_text
              end
            end
            if @question_group.examen?
              column_names << "Total"
            end
            sheet.add_row column_names

            @answer_groups.each do |answer_group|
              column_contents = []
              total = 0.0
              total_user = 0.0
              @question_group.questions.each do |question|
                answer = answer_group.answers.where(:question => question).first
                if answer
                  if answer.question.type == "Rapidfire::Questions::File"
                    column_contents << "#{request.protocol}#{request.host_with_port}#{answer.document.url}"

                  elsif @question_group.examen? && answer.question.points > 0
                    column_contents << answer.answer_text
                    if answer.right?
                      total_user += answer.question.points
                    end
                    total += answer.question.points
                  else
                    column_contents << answer.answer_text
                  end
                else
                  column_contents << ""
                end
              end
              if @question_group.examen?
                column_contents << total_user.prettify
              end
              sheet.add_row column_contents
            end
          end
          p.use_shared_strings = true
          p.serialize("posts.xlsx")
          send_data p.to_stream.read, :filename => "Résultats - #{@question_group.name}.xlsx"
        end
      end
    end

    private
    def question_group_params
      if Rails::VERSION::MAJOR == 4
        params.require(:question_group).permit(:name, :header, :type, :type_cd, :final_text, :final_link)
      else
        params[:question_group]
      end
    end
  end
end

app/views/rapidfire/questions/_form.html.haml
= form_for [@question_group, question], :html => {:class => "form-horizontal"} do |f|
  - unless question.errors.empty?
    %ul
      - question.errors.full_messages.each do |message|
        %li= message
  
  .row
    .col-xs-12
      .form-group
        = f.label :type, :class => "form-group-title"
        %br
        = f.select :type, ::Rapidfire::QuestionForm::QUESTION_TYPES, {}, id: "question_type"

      .form-group
        = f.label :question_text, :class => "form-group-title"
        = f.text_field :question_text, :class => "form-control"

      .form-group
        = f.label :question_text_cn, :class => "form-group-title"
        = f.text_field :question_text_cn, :class => "form-control"

      .form-group
        = f.label :answer_options, :class => "form-group-title"
        = f.text_area :answer_options, rows: 4, :class => "text optional input-xlarge", :class => "form-control"
      
      - if @question_group.examen?
        .form-group
          = f.label :right_answers, :class => "form-group-title"
          = f.text_area :right_answers, :class => "form-control"
        .form-group
          = f.label :points, :class => "form-group-title"
          = f.text_field :points, :class => "form-control"

      .form-group
        = f.label :question_condition, :class => "form-group-title"
        %br
        = f.collection_select(:question_condition_id, @question_group.questions, :id, :question_text, {:selected => question.question_condition_id, include_blank: "-"}, {})

      .form-group
        = f.label :question_condition_answers, :class => "form-group-title"
        = f.text_area :question_condition_answers, :class => "form-control"

      .form-group
        = f.label :position, :class => "form-group-title"
        = f.text_field :position, :class => "form-control"

      .form-group
        = f.label :col_size, :class => "form-group-title"
        %br
        = f.select :col_size, (1..12), :selected => question.col_size

      .form-group
        = f.label t('clear'), :class => "form-group-title"
        %br
        = f.select :clear_cd, enum_option_pairs(Rapidfire::Question, :clear, true)

      .form-group
        .checkbox
          %label
            = f.check_box :private
            = f.label :private, :class => "form-group-title"

      .form-group
        .checkbox
          %label
            = f.check_box :answer_presence
            Obligatoire

      .form-group
        .checkbox
          %label
            = f.check_box :show_in_pdf
            Afficher dans le PDF

    %div{:style => "display:none;"}
      %h4
        Other options
      %hr

      .form-group
        = f.label :answer_minimum_length, :class => "form-group-title"
        = f.text_field :answer_minimum_length, :class => "form-control"

      .form-group
        = f.label :answer_maximum_length, :class => "form-group-title"
        = f.text_field :answer_maximum_length, :class => "form-control"

      .form-group
        = f.label :answer_greater_than_or_equal_to, :class => "form-group-title"
        = f.text_field :answer_greater_than_or_equal_to, :class => "form-control"

      .form-group
        = f.label :answer_less_than_or_equal_to, :class => "form-group-title"
        = f.text_field :answer_less_than_or_equal_to, :class => "form-control"

  .form-group
    = f.submit t("submit"), :class => "btn btn-primary"

app/views/rapidfire/questions/_question.html.haml
%tr{:id=>"question_#{question.id}"}
  %td
    .handle-sort.btn-default.btn.btn-xs
      %i.fa.fa-arrows
  %td{:style => "padding-left:#{2*conditional_question_ids(question).split(" ").size}%"}
    - conditional_question(question).reverse.each do |q|
      - if q.question_condition
        - title = q.question_condition.question_text + " " + q.question_condition_answers
        %i.fa.fa-arrow-circle-right{:"data-toggle"=>"tooltip", :title => title, :style => "cursor:pointer;"}
    = question.question_text
  %td
    - question_name = question.type.to_s.split("::").last.downcase
    = t("activerecord.models.rapidfire.questions."+question_name.downcase)
  %td= question.rules[:presence]
  %td= question.show_in_pdf
  %td
    - if question.question_group.examen? 
      = question.points.prettify if question.points
  %td= question.col_size
  %td= question.clear
  %td= question.private
  %td.actions
    = link_to [:edit, question.question_group, question], :class => "btn btn-primary btn-xs", :title => t('edit'), :"data-toggle"=>"tooltip" do
      %i.fa.fa-edit
    - if Rapidfire::Answer.where(:question_id => question.id).count > 0
      = link_to [question.question_group, question], :method => :delete, data: { confirm: t("delete_confirmation_already_answers") }, :class => "btn btn-danger btn-xs", :title => t('delete'), :"data-toggle"=>"tooltip" do
        %i.fa.fa-trash-o
    - else
      = link_to [question.question_group, question], :method => :delete, data: { confirm: t("delete_confirmation") }, :class => "btn btn-danger btn-xs", :title => t('delete'), :"data-toggle"=>"tooltip" do
        %i.fa.fa-trash-o
    %input{:type => "hidden", :id => "question_#{question.id}_position", :name => "positions[questions][#{question.id}]", :value => question.position}

app/views/rapidfire/questions/edit.html.erb
<%= render partial: 'form', locals: {question: @question} %>

app/views/rapidfire/questions/index.html.haml
%h1
  = @question_group.name
%hr
= link_to new_question_group_question_path(@question_group), :class => "btn btn-primary", :style => "float:right;" do
  %i.fa.fa-plus-circle{:style => "margin-right:5px;"}
  = t("questions.new_question")
= link_to new_question_group_fieldset_path(@question_group), :class => "btn btn-primary", :style => "float:right;" do
  %i.fa.fa-plus-circle{:style => "margin-right:5px;"}
  = t("questions.new_fieldset")

%div
  Type :
  = @question_group.type
%div
  Auteur :
  = @question_group.user.email
%div
  Réponses :
  = "#{Rapidfire::AnswerGroup.where(:question_group => @question_group).count}"
- if @question_group.examen?
  %br
  Total de points :
  - total = 0
  - @questions.each{|q| total+=q.points if q.points}
  = total.prettify if total > 0
%hr

= form_tag update_positions_question_group_path(@question_group), :method => :post do
  %table.table
    %tr
      %th{:style => "width:60px;"}
      %th Titre
      %th Type
      %th Obligatoire
      %th PDF
      %th Points
      %th Colonnes
      %th Ligne
      %th Privé
      %th{:style => "width:100px;"}
    %tbody.sortable
      - if @elements.any?
        - @elements.each do |element|
          - if element.class == Rapidfire::Fieldset
            = render "rapidfire/fieldsets/fieldset", :fieldset => element
          - else
            = render "rapidfire/questions/question", :question => element
      -#= render partial: "question", collection: @questions

  = submit_tag "Valider les positions", :class => "btn btn-primary"

app/views/rapidfire/questions/new.html.erb
<%= render partial: 'form', locals: {question: @question} %>