config/routes.rb
Rapidfire::Engine.routes.draw do
  resources :question_groups do
    get 'results', on: :member
    post "update_positions", on: :member
    get 'duplicate', on: :member
    get :final, :on => :member
    resources :questions
    resources :fieldsets
    resources :answer_groups, only: [:new, :show, :create, :edit, :update]
  end
  root :to => "question_groups#index"
end

app/models/rapidfire/answer.rb
module Rapidfire
  class Answer < ActiveRecord::Base
    belongs_to :question
    belongs_to :answer_group, inverse_of: :answers

    validates :question, :answer_group, presence: true
    validate :verify_answer_text, :if => "question.present?"

    # has_attached_file :document
    # do_not_validate_attachment_file_type :document

    has_many :documents, :dependent => :destroy
    accepts_nested_attributes_for :documents, :allow_destroy => true

    if Rails::VERSION::MAJOR == 3
      attr_accessible :question_id, :answer_group, :answer_text, :documents, :documents_attributes
    end

    def right?
      if self.question.right_answers
        if self.question.type == "Rapidfire::Questions::Checkbox"
          self.question.right_answers.split("\r\n").sort == self.answer_text.split(',').sort
        else
          self.question.right_answers.split("\r\n").include? self.answer_text
        end
      else
        true
      end
    end

    private
    def verify_answer_text
      question.validate_answer(self)
    end
  end
end

app/models/rapidfire/answer_group.rb
module Rapidfire
  class AnswerGroup < ActiveRecord::Base
    belongs_to :question_group
    belongs_to :user, polymorphic: true
    has_many   :answers, inverse_of: :answer_group, autosave: true

    if Rails::VERSION::MAJOR == 3
      attr_accessible :question_group, :user
    end


    def points
      total = 0
      answers.each do |answer|
        total += answer.right? ? answer.question.points : 0
      end
      total
    end
  end
end

app/models/rapidfire/document.rb
module Rapidfire
  class Document < ActiveRecord::Base
    belongs_to :answer

    has_attached_file :asset
    do_not_validate_attachment_file_type :asset
  end
end

app/models/rapidfire/fieldset.rb
module Rapidfire
  class Fieldset < ActiveRecord::Base
    belongs_to :question_group, :inverse_of => :fieldsets

    if Rails::VERSION::MAJOR == 3
      attr_accessible :question_group, :title, :title_cn, :description, :position, :private
    end
  end
end

app/models/rapidfire/question.rb
module Rapidfire
  class Question < ActiveRecord::Base
    belongs_to :question_group, :inverse_of => :questions
    has_many   :answers, :dependent => :destroy

    default_scope { order(:position) }

    validates :question_group, :question_text, :presence => true
    serialize :validation_rules

    has_attached_file :file

    belongs_to :question_condition, :class_name => Rapidfire::Question

    as_enum :clear, :none => 0, :both => 1

    if Rails::VERSION::MAJOR == 3
      attr_accessible :question_group, :question_text, :validation_rules, :answer_options, :right_answers, :points, :show_in_pdf, :question_text_cn
      attr_accessible :question_condition_id, :question_condition_answers, :col_size, :clear_cd, :private
    end

    def self.inherited(child)
      child.instance_eval do
        def model_name
          Question.model_name
        end
      end

      super
    end

    def rules
      validation_rules || {}
    end

    def mandatory?
      if rules[:presence] == "1"
        true
      else
        false
      end
    end

    # answer will delegate its validation to question, and question
    # will inturn add validations on answer on the fly!
    def validate_answer(answer)
      if rules[:presence] == "1"
        answer.validates_presence_of :answer_text
      end

      if rules[:minimum].present? || rules[:maximum].present?
        min_max = { minimum: rules[:minimum].to_i }
        min_max[:maximum] = rules[:maximum].to_i if rules[:maximum].present?

        answer.validates_length_of :answer_text, min_max
      end
    end
  end
end

app/models/rapidfire/question_group.rb
module Rapidfire
  class QuestionGroup < ActiveRecord::Base
    belongs_to :user
    has_many  :questions, :dependent => :destroy
    has_many  :fieldsets, :dependent => :destroy
    validates :name, :presence => true

    before_destroy :destroy_answer_groups

    as_enum :type, :examen => 1, :formulaire => 0

    if Rails::VERSION::MAJOR == 3
      attr_accessible :name, :type_cd, :type, :header, :final_text, :final_link
    end

    def points
      total = 0
      questions.each do |q|
        total += q.points
      end
      total
    end

    def elements
      (questions + fieldsets).sort_by do |e|
        e.position || (questions + fieldsets).count
      end
    end

    def destroy_answer_groups
      AnswerGroup.where(:question_group_id => self.id).destroy_all
    end
  end
end

app/models/rapidfire/questions/checkbox.rb
module Rapidfire
  module Questions
    class Checkbox < Rapidfire::Question
      validates :answer_options, :presence => true

      def options
        answer_options.split(/\r?\n/)
      end

      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          answer.answer_text.split(",").each do |value|
            answer.errors.add(:answer_text, :invalid) unless options.include?(value)
          end
        end
      end
    end
  end
end

app/models/rapidfire/questions/date.rb
module Rapidfire
  module Questions
    class Date < Rapidfire::Question
      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          begin  ::Date.parse(answer.answer_text.to_s)
          rescue ArgumentError => e
            answer.errors.add(:answer_text, :invalid)
          end
        end
      end
    end
  end
end

app/models/rapidfire/questions/datetime.rb
module Rapidfire
  module Questions
    class Datetime < Rapidfire::Question
      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          begin  ::DateTime.parse(answer.answer_text.to_s)
          rescue ArgumentError => e
            answer.errors.add(:answer_text, :invalid)
          end
        end
      end
    end
  end
end

app/models/rapidfire/questions/email.rb
module Rapidfire
  module Questions
    class Email < Rapidfire::Question
      def validate_answer(answer)
        super(answer)
        if rules[:presence] == "1" || answer.answer_text.present?
          answer.errors.add(:answer_text, :invalid) unless answer.answer_text =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
        end
      end
    end
  end
end

app/models/rapidfire/questions/file.rb
module Rapidfire
  module Questions
    class File < Rapidfire::Question
    end
  end
end

app/models/rapidfire/questions/long.rb
module Rapidfire
  module Questions
    class Long < Rapidfire::Question
    end
  end
end

app/models/rapidfire/questions/radio.rb
module Rapidfire
  module Questions
    class Radio < Select
    end
  end
end

app/controllers/rapidfire/answer_groups_controller.rb
module Rapidfire
  class AnswerGroupsController < Rapidfire::ApplicationController
    before_filter :find_question_group!

    def show
      @answer_group_builder = AnswerGroupBuilder.new(answer_group_params)
      @answer_group = AnswerGroup.find(params[:id])

      respond_to do |format|
        format.html
        format.pdf do
          render :pdf => "file_name", 
            :footer => { :right => '[page] of [topage]' },
            :show_as_html => false
        end
      end
    end

    def new
      @answer_group_builder = AnswerGroupBuilder.new(answer_group_params)

      respond_to do |format|
        format.html
        format.pdf do
          render :pdf => "file_name", 
            :footer => { :right => '[page] of [topage]' },
            :show_as_html => false
        end
      end
    end

    def create
      @answer_group_builder = AnswerGroupBuilder.new(answer_group_params)
      if @answer_group_builder.save
        if !@answer_group_builder.question_group.final_text.blank?
          redirect_to final_question_group_path(@answer_group_builder.question_group)
        elsif !@answer_group_builder.question_group.final_link.blank?
          redirect_to @answer_group_builder.question_group.final_link
        else
          redirect_to question_groups_path
        end
      else
        render :new
      end
    end

    def edit
      @answer_group_builder = AnswerGroupBuilder.new(answer_group_params)
      @answer_group = AnswerGroup.find(params[:id])
    end

    def update
      @answer_group = AnswerGroup.find(params[:id])

      params[:answer_group].each do |question_id, answer_attributes|
        if answer = @answer_group.answers.find { |a| a.question_id.to_s == question_id.to_s }
          text = answer_attributes[:answer_text]
          answer.answer_text = text.is_a?(Array) ? strip_checkbox_answers(text).join(',') : text
          #answer.answer_text = text.is_a?(Array) ? text.join(',') : text

          if answer.question.type == "Rapidfire::Questions::File"
            answer.documents_attributes = answer_attributes[:documents_attributes]
          end
        else
          answer = Answer.new(:question_id => question_id)

          text = answer_attributes[:answer_text]
          answer.answer_text = text.is_a?(Array) ? strip_checkbox_answers(text).join(',') : text
          #answer.answer_text = text.is_a?(Array) ? text.join(',') : text

          if answer.question.type == "Rapidfire::Questions::File"
            answer.documents_attributes = answer_attributes[:documents_attributes]
          end

          @answer_group.answers << answer
        end
      end
      if @answer_group.save
        if !@answer_group.question_group.final_text.blank?
          redirect_to final_question_group_path(@answer_group.question_group)
        elsif !@answer_group.question_group.final_link.blank?
          redirect_to @answer_group.question_group.final_link
        else
          redirect_to question_groups_path, :notice  => "Successfully updated."
        end
      else
        render :action => 'edit'
      end
      # if @answer_group.update_attributes(params[:answer_group])
      #   redirect_to question_groups_path, :notice  => "Successfully updated."
      # else
      #   render :action => 'edit'
      # end
    end

    private

    def strip_checkbox_answers(text)
      text.reject(&:blank?).reject { |t| t == "0" }
    end
    
    def find_question_group!
      @question_group = QuestionGroup.find(params[:question_group_id])
    end

    def answer_group_params
      answer_params = { params: params[:answer_group] }
      answer_params.merge(user: current_user, question_group: @question_group)
    end
  end
end

app/controllers/rapidfire/application_controller.rb
module Rapidfire
  class ApplicationController < ::ApplicationController
    helper_method :can_administer?

    def authenticate_administrator!
      unless can_administer?
        raise Rapidfire::AccessDenied.new("cannot administer questions")
      end
    end
  end
end

app/controllers/rapidfire/fieldsets_controller.rb
module Rapidfire
  class FieldsetsController < Rapidfire::ApplicationController
    respond_to :html, :js

    before_filter :find_question_group!
    before_filter :find_fieldset!, :only => [:edit, :update, :destroy]

    def new
      @fieldset = Rapidfire::Fieldset.new(:question_group => @question_group)
      @fieldset.position = @question_group.elements.count
      respond_with(@fieldset)
    end

    def create
      #form_params = params[:fieldset].merge(:question_group => @question_group)
      @fieldset = Rapidfire::Fieldset.new(ad_params.merge(:question_group => @question_group))
      @fieldset.save

      respond_with(@fieldset, location: index_location)
    end

    def edit
      respond_with(@fieldset)
    end

    def update
      #form_params = params[:fieldset].merge(:fieldset => @fieldset)
      @fieldset.update_attributes(ad_params)

      respond_with(@fieldset, location: index_location)
    end

    def destroy
      @fieldset.destroy

      respond_with(@fieldset, location: index_location)
    end

    private
    def ad_params
      params.require(:fieldset).permit(:question_group, :title, :title_cn, :description, :position, :private)
    end

    def find_question_group!
      @question_group = QuestionGroup.find(params[:question_group_id])
    end

    def find_fieldset!
      @fieldset = @question_group.fieldsets.find(params[:id])
    end

    def index_location
      rapidfire.question_group_questions_url(@question_group)
    end
  end
end

app/controllers/rapidfire/question_groups_controller.rb
module Rapidfire
  class QuestionGroupsController < Rapidfire::ApplicationController
    before_filter :authenticate_administrator!, except: [:final]
    respond_to :html, :js
    respond_to :json, only: :results

    def index
      @question_groups = QuestionGroup.all
      respond_with(@question_groups)
    end

    def new
      @question_group = QuestionGroup.new
      respond_with(@question_group)
    end

    def create
      @question_group = QuestionGroup.new(question_group_params)
      @question_group.user = current_user
      
      if @question_group.save

      #respond_with(@question_group, location: rapidfire.question_groups_url)

        redirect_to question_group_questions_path(@question_group)
      else
        render :new
      end
    end

    def final
      @question_group = QuestionGroup.find(params[:id])
    end

    def edit
      @question_group = QuestionGroup.find(params[:id])
      respond_with(@question_group)
    end

    def update_positions
      @question_group = QuestionGroup.find(params[:id])

      if !params[:positions][:questions].nil?
        params[:positions][:questions].each do |element_id, position|
          Question.find(element_id).update_attributes(:position => position)
        end
      end

      if !params[:positions][:fieldsets].nil?
        params[:positions][:fieldsets].each do |element_id, position|
          Rapidfire::Fieldset.find(element_id).update_attributes(:position => position)
        end
      end
      redirect_to question_group_questions_path(@question_group), :notice  => "Positions mises à jour"
    end

    def duplicate
      model = QuestionGroup.find(params[:id])
      @question_group = model.dup
      @question_group.name = "Copie de #{@question_group.name}"
      model.questions.each do |question|
        @question_group.questions << question.dup
      end

      if @question_group.save
        redirect_to edit_question_group_path(@question_group)
      end
    end

    def update
      @question_group = QuestionGroup.find(params[:id])
      params.permit!
      if @question_group.update_attributes(params[:question_group])
        redirect_to question_groups_path, :notice  => "Successfully updated."
      else
        render :action => 'edit'
      end
    end

    def destroy
      @question_group = QuestionGroup.find(params[:id])
      @question_group.destroy

      respond_with(@question_group)
    end

    def results
      @question_group = QuestionGroup.find(params[:id])
      @answer_groups = Rapidfire::AnswerGroup.where(:question_group => params[:id])
      @question_group_results = QuestionGroupResults.new(question_group: @question_group).extract

      respond_to do |format|
        format.html { respond_with(@question_group_results, root: false) }
        format.xls do
          p = Axlsx::Package.new
          p.workbook.add_worksheet(:name => "Résultats") do |sheet|
            column_names = []
            @question_group.questions.each do |question|
              if @question_group.examen? && (question.points && question.points > 0)
                column_names << "#{question.question_text} [#{question.points.prettify} points]"
              else
                column_names << question.question_text
              end
            end
            if @question_group.examen?
              column_names << "Total"
            end
            sheet.add_row column_names

            @answer_groups.each do |answer_group|
              column_contents = []
              total = 0.0
              total_user = 0.0
              @question_group.questions.each do |question|
                answer = answer_group.answers.where(:question => question).first
                if answer
                  if answer.question.type == "Rapidfire::Questions::File"
                    column_contents << "#{request.protocol}#{request.host_with_port}#{answer.document.url}"

                  elsif @question_group.examen? && answer.question.points > 0
                    column_contents << answer.answer_text
                    if answer.right?
                      total_user += answer.question.points
                    end
                    total += answer.question.points
                  else
                    column_contents << answer.answer_text
                  end
                else
                  column_contents << ""
                end
              end
              if @question_group.examen?
                column_contents << total_user.prettify
              end
              sheet.add_row column_contents
            end
          end
          p.use_shared_strings = true
          p.serialize("posts.xlsx")
          send_data p.to_stream.read, :filename => "Résultats - #{@question_group.name}.xlsx"
        end
      end
    end

    private
    def question_group_params
      if Rails::VERSION::MAJOR == 4
        params.require(:question_group).permit(:name, :header, :type, :type_cd, :final_text, :final_link)
      else
        params[:question_group]
      end
    end
  end
end

app/views/rapidfire/question_groups/_form.html.erb
<h1><%= question_group.new_record? ? "Nouveau formulaire" : "Edition du formulaire" %></h1>
<hr>
<%= form_for question_group do |f| %>
  <%- if question_group.errors.any? %>
    <ul>
      <%- question_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    <%= f.label :name, :class => "form-group-title" %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :type, :class => "form-group-title" %>
    <br>
    <%= f.select :type_cd, enum_option_pairs(Rapidfire::QuestionGroup, :type, true) %>
  </div>

  <div class="form-group">
    <%= f.label :header, :class => "form-group-title" %>
    <%= f.text_area :header, :class => "form-control tinymce" %>
  </div>
  <div class="form-group">
    <%= f.label :final_text, :class => "form-group-title" %>
    <%= f.text_area :final_text, :class => "form-control tinymce" %>
  </div>
  <div class="form-group">
    <%= f.label :final_link, :class => "form-group-title" %>
    <%= f.text_field :final_link, :class => "form-control" %>
    <p class="help-block"><%= f.label :final_link_help %></p>
  </div>
  <%= tinymce %>

  <div class="form-group">
    <%= f.submit t("submit"), :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/rapidfire/question_groups/_question_group.html.erb
<tr id= "question_group_<%= question_group.id %>">
  <td><%= question_group.name %></td>
  <td><%= question_group.type %></td>
  <td><%= question_group.questions.count %></td>
  <td><%= question_group.user.email if question_group.user %></td>
  <td class="actions">
      <%= link_to new_question_group_answer_group_path(question_group), :class => "btn btn-xs btn-primary", :title => t('fill_form'), :"data-toggle"=>"tooltip" do %>
        <i class="fa fa-check-square-o"></i>
      <% end %>
      <%= link_to new_question_group_answer_group_path(question_group, :format => :pdf), :class => "btn btn-xs btn-primary", :title => t('export_pdf'), :"data-toggle"=>"tooltip" do %>
        <i class="fa fa-file-pdf-o"></i>
      <% end %>
      <% if can_administer? %>
        <%= link_to edit_question_group_path(question_group), :class => "btn btn-xs btn-primary", :title => t('edit'), :"data-toggle"=>"tooltip" do %>
          <i class="fa fa-edit"></i>
        <% end %>
        <%= link_to question_group_questions_path(question_group), :class => "btn btn-xs btn-primary", :title => t('edit_questions'), :"data-toggle"=>"tooltip" do %>
          <i class="fa fa-question-circle"></i>
        <% end %>
        <%= link_to [:results, question_group], :class => "btn btn-xs btn-primary", :title => t('results'), :"data-toggle"=>"tooltip" do %>
          <i class="fa fa-graduation-cap"></i>
        <% end %>
        <%= link_to duplicate_question_group_path(question_group), :class => "btn btn-xs btn-primary", :title => t('duplicate'), :"data-toggle"=>"tooltip" do %>
          <i class="fa fa-copy"></i>
        <% end %>
        <%= link_to [question_group], method: :delete, data: { confirm: t("delete_confirmation") }, :class => "btn btn-xs btn-danger", :title => t('delete'), :"data-toggle"=>"tooltip" do %>
          <i class="fa fa-trash-o"></i>
        <% end %>
      <% end %>
  </td>
</tr>

app/views/rapidfire/question_groups/duplicate.html.haml
= render partial: 'form', locals: {question_group: @question_group}

app/views/rapidfire/question_groups/edit.html.erb
<%= render partial: 'form', locals: {question_group: @question_group} %>

app/views/rapidfire/question_groups/final.html.haml
= raw @question_group.final_text

-#= link_to "Terminer", @question_group.final_link if @question_group.final_link

app/views/rapidfire/question_groups/index.html.erb
<% if can_administer? %>
  <%= link_to new_question_group_path, :class => "btn btn-primary", :style => "float:right;" do %>
    <i class="fa fa-plus-circle" style="margin-right:5px;"></i>
    Nouveau questionnaire
  <% end %>
<% end %>
<h1>
  Liste des questionnaires
</h1>
<hr/>

<table class="table">
  <tr>
    <th>Nom</th>
    <th>Type</th>
    <th>Questions</th>
    <th>Auteur</th>
    <th width="330"></th>
  </tr>
  <tbody>
    <%= render partial: "question_group", collection: @question_groups %>
  </tbody>
</table>

app/views/rapidfire/question_groups/new.html.erb
<%= render partial: 'form', locals: {question_group: @question_group} %>

app/views/rapidfire/question_groups/results.html.haml
%h1
  = @question_group.name
  = link_to [:results, @question_group, :format => :xls], :class => "btn btn-primary", :style => "float:right;" do
    .fa.fa-file-excel-o{:style=>"margin-right:5px"}
    Export Excel
%h6
  = "Résultats du questionnaire"
<hr>
%table.table
  %tr
    - @question_group.questions.each do |question|
      - if question.mandatory?
        %th
          = question.question_text
          - if @question_group.examen? && (question.points && question.points > 0)
            .small= "[#{question.points.prettify} points]"
    - if @question_group.examen?
      %th Total
    - if can_administer?
      %th
  - @answer_groups.each do |answer_group|
    %tr
      - total = 0.0
      - total_user = 0.0
      - @question_group.questions.each do |question|
        - answer = answer_group.answers.where(:question => question).first
        - if answer
          - if answer.question.type == "Rapidfire::Questions::File"
            - if question.mandatory?
              %td
                - if answer.documents.any?
                  - answer.documents.each do |doc|
                    = link_to doc.asset_file_name, doc.asset.url

          - elsif @question_group.examen? && (!answer.question.points.nil? && answer.question.points > 0)
            - if question.mandatory?
              %td{:class => "#{answer.right? ? 'alert-success' : 'alert-danger'}"}
                = answer.answer_text
            - if answer.right?
              - total_user += answer.question.points
            - total += answer.question.points
          - else
            - if question.mandatory?
              %td= answer.answer_text
        - else
          %td

      - if @question_group.examen?
        %td
          = "#{total_user.prettify}/#{total.prettify}"
      - if can_administer?
        %td.actions
          = link_to question_group_answer_group_path(@question_group, answer_group), :class => "btn btn-xs btn-primary", :title => "Voir", :"data-toggle"=>"tooltip" do
            %i.fa.fa-eye
          = link_to edit_question_group_answer_group_path(@question_group, answer_group), :class => "btn btn-xs btn-primary", :title => t('edit'), :"data-toggle"=>"tooltip" do
            %i.fa.fa-edit